"""second

Revision ID: 05d2559370d7
Revises: b34dfc8ea9ff
Create Date: 2022-12-02 21:07:23.655193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d2559370d7'
down_revision = 'b34dfc8ea9ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
