"""second

Revision ID: b34dfc8ea9ff
Revises: 98fe15e40459
Create Date: 2022-12-02 20:59:54.846912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34dfc8ea9ff'
down_revision = '98fe15e40459'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
