"""Add field

Revision ID: b68d562a861c
Revises: ce5a1a760735
Create Date: 2022-12-02 21:32:57.906263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68d562a861c'
down_revision = 'ce5a1a760735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
